#----------------------------------------------------------------------------------
# Image
#----------------------------------------------------------------------------------
image: node:latest

#----------------------------------------------------------------------------------
# Pre install pour Heroku
#----------------------------------------------------------------------------------
before_script: 
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl


#----------------------------------------------------------------------------------
# Stages
#----------------------------------------------------------------------------------
stages:
  - dependencies
  - build
  - test
  - dev
  - public_publish

install:
  stage: dependencies
  script: 
    - npm i
  artifacts:
    expire_in: 1h
    paths:
    - node_modules/
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

#tests:
 # stage: test
 # dependencies:
 #   - install
 # script:
  #  - npm run jest

build:
  stage: build
  variables:
    BUILD_CONFIG: 'production'
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    expire_in: 1h
    paths:
    - dist/

livraison_dev:
    stage: dev
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$APP_DEV --api-key=$HEROKU_API_KEY_DEV
    only:
      - develop

livraison_prod:
    stage: public_publish
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$APP_PROD --api-key=$HEROKU_API_KEY_PROD
    only:
      - prod